name: M6-2 Terraform Apply Workflow

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: choice
        options:
          - 'v0.0.1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"Workflow URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id}}\"}" $DISCORD_WEBHOOK_URL Send Notification to Discord

