name: M6-2 Terraform Apply Workflow

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: choice
        options:
          - 'v0.0.1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Send Notification to Discord
        uses: DiscordWebhook-Action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: 'Deployment approved and applied! Workflow URL: ${{ github.event.workflow_run.html_url }}'

